export const PROVIDERS = [
  {
    code: 'odtu',
    website: 'https://odtuteknokent.com.tr/tr/firmalar/tum-firmalar.php',
    shortTitle: 'Odtü Teknokent',
    fullTitle: 'Odtü Teknokent Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'tgb_ankaraodtu@odtuteknokent.com.tr',
    phone: '(312) 987 35 00',
    address: 'ODTÜ TEKNOKENT İKİZLER BİNASI B BLOK NO:ZK-1 Çankaya/Ankara',
  },
  {
    code: 'hacettepe',
    website: 'https://hacettepeteknokent.com.tr',
    shortTitle: 'Hacettepe Teknokent',
    fullTitle: 'Hacettepe Üniversitesi Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'tgb_ankarahacettepe@hacettepeteknokent.com.tr',
    phone: '(312) 297 71 62',
    address: 'Hacettepe Üniversitesi Beytepe Kampusü Hacettepe Teknokent 1.Ar-Ge Binası 06800 Beytepe/Ankara',
  },
  {
    code: 'ankarauniversity',
    website: 'https://ankarateknokent.com/firmalar-portfolio/',
    shortTitle: 'Ankara Üniversitesi Teknokent',
    fullTitle: 'Ankara Üniversitesi Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'info@ankarateknokent.com',
    phone: '(312) 485 37 18',
    address: 'Ankara Üniversitesi Teknoloji Geliştirme Bölgesi Yönetici A.Ş. Bahçelievler Mah. 319. Sok. No: 35 A Blok İdari Bina Gölbaşı/Ankara',
  },
  {
    code: 'teknoparkankara',
    website: 'https://www.teknoparkankara.com.tr/Firmalar.html',
    shortTitle: 'Teknopark Ankara',
    fullTitle: 'Ankara Teknopark Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'bilgi@teknoparkankara.com.tr',
    phone: '(312) 395 62 27',
    address: 'Ankara Teknopark TGB Yerleşkesi İvedik Osb Mh. 2224. Cd No:1 Yenimahalle/Ankara',
  },
  {
    code: 'asoteknopark',
    website: 'https://www.asoteknopark.com.tr/?page_id=1606',
    shortTitle: 'ASO Teknopark',
    fullTitle: 'ASO Teknopark Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'tgb_ankaraasoteknopark@asoteknopark.com.tr',
    phone: '(550) 006 40 00',
    address: 'Ahi Evran Osb Mah. Erkunt Cad. No: 1/2 Sincan/Ankara',
  },
  {
    code: 'gaziuniversity',
    website: 'https://api.gaziteknopark.com.tr/Unit/GetUnitByPaginationAll',
    shortTitle: 'Gazi Teknopark',
    fullTitle: 'Gazi Teknopark Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'info@gaziteknopark.com.tr',
    phone: '(312) 484 88 53',
    address: 'Bahçelievler Mah. 323/1 Cad. Gazi Üniversitesi Teknokent Binası A Blok No: 10/50A/40 06830 Gölbaşı/Ankara',
  },
];
