export const PROVIDERS = [
  {
    code: 'odtu',
    website: 'https://odtuteknokent.com.tr/tr/firmalar/tum-firmalar.php',
    shortTitle: 'Odtü Teknokent',
    fullTitle: 'Odtü Teknokent Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'tgb_ankaraodtu@odtuteknokent.com.tr',
    phone: '(312) 987 35 00',
    address: 'ODTÜ TEKNOKENT İKİZLER BİNASI B BLOK NO:ZK-1 ÇANKAYA/ANKARA',
  },
  {
    code: 'hacettepe',
    website: 'https://hacettepeteknokent.com.tr',
    shortTitle: 'Hacettepe Teknokent',
    fullTitle: 'Hacettepe Üniversitesi Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'tgb_ankarahacettepe@hacettepeteknokent.com.tr',
    phone: '(312) 297 71 62',
    address: 'Hacettepe Üniversitesi Beytepe Kampusü Hacettepe Teknokent 1.Ar-Ge Binası 06800 Beytepe / ANKARA',
  },
  {
    code: 'ankarauniversity',
    website: 'https://ankarateknokent.com/firmalar-portfolio/',
    shortTitle: 'Ankara Üniversitesi Teknokent',
    fullTitle: 'Ankara Üniversitesi Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'info@ankarateknokent.com',
    phone: '(312) 485 37 18',
    address: 'Ankara Üniversitesi Teknoloji Geliştirme Bölgesi Yönetici A.Ş. Bahçelievler Mah. 319. Sok. No: 35 A Blok İdari Bina Gölbaşı/Ankara',
  },
  {
    code: 'teknoparkankara',
    website: 'https://www.teknoparkankara.com.tr/Firmalar.html',
    shortTitle: 'Teknopark Ankara',
    fullTitle: 'Ankara Teknopark Teknoloji Geliştirme Bölgesi',
    cityId: 6,
    email: 'bilgi@teknoparkankara.com.tr',
    phone: '(312) 395 62 27',
    address: 'Ankara Teknopark TGB Yerleşkesi İvedik Osb Mh. 2224. Cd No:1 Yenimahalle / Ankara',
  },
];
